                                       Web Scraping Assignment - 4

1.Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [1]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="e1ef18eab07d475a932d13396fc327b2")>

In [2]:
# Getting the webpage of mentioned url 
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

In [3]:
#creating empty list
Rank=[]
Name=[]
Artist=[]
Upload_date=[]
Views=[]

Scrapping the data

In [4]:
#Scraping data of rank details
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[1]')[:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')
        #Scraping data of video names
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[2]')[:30]:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')

#Scraping data of artist name
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[3]')[:30]:
        Artist.append(i.text)
except NoSuchElementException:        
    Artist.append('-')
    
#Scraping data of upload dates
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[5]')[:30]:
        Upload_date.append(i.text)
except NoSuchElementException:        
    Upload_date.append('-')
    
    
#Scraping data of views
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[4]')[:30]:
        Views.append(i.text)
except NoSuchElementException:
    Views.append('-')

In [5]:
#DATA FRAMEING
Youtube=pd.DataFrame({})
Youtube['Rank'] = Rank
Youtube['Name'] = Name
Youtube['Artist'] = Artist
Youtube['Uploaded Date'] = Upload_date
Youtube['Views'] = Views

In [6]:
#Printing data frame
Youtube

,Rank,Name,Artist,Uploaded Date,Views
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.00
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.05
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.57
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.89
4,5.,"""Shape of You""[16]",Ed Sheeran,"January 30, 2017",5.88
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.74
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.08
7,8.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.79
8,9.,"""Wheels on the Bus""[25]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.77
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,"February 27, 2018",4.76
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.64
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.18
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.80
14,15.,"""Roar""[35]",Katy Perry,"September 5, 2013",3.70
15,16.,"""Counting Stars""[36]",OneRepublic,"May 31, 2013",3.70
16,17.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.67
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.62
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.53
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.46
20,21.,"""Dark Horse""[41]",Katy Perry,"February 20, 2014",3.42
21,22.,"""Waka Waka (This Time for Africa)""[42]",Shakira,"June 4, 2010",3.40
22,23.,"""Faded""[43]",Alan Walker,"December 3, 2015",3.38
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.36
24,25.,"""Girls Like You""[45]",Maroon 5,"May 31, 2018",3.35
25,26.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.33
26,27.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.31
27,28.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.31
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.26
29,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,"June 14, 2018",3.24

Q2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1 st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [7]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="3fd992173a3879fa7d0d97d9ee59a65f")>

In [8]:
# Connecting the website
url = " https://www.bcci.tv/"
driver.get(url)
time.sleep(2)

In [9]:
#going to international fixtures page
International = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a') 
International.click()

In [10]:
#Creating Empty List
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]

#screaping series
try:  
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
    
#scrapping Place
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
    
#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
    #Scrapping Time
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))
except NoSuchElementException:
    Time.append('-')

    
# Creating Dataframe

Int_Fixtures=pd.DataFrame({})

Int_Fixtures['Match Title']=Name
Int_Fixtures['Series']=Series
Int_Fixtures['Place']=Place
Int_Fixtures['Date']=Date
Int_Fixtures['Time']=Time
Int_Fixtures

,Match Title,Series,Place,Date,Time
0,NaN,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,"Steyn City School Ground,",31 DEC 2022,1:30 PM
1,NaN,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,"Steyn City School Ground,",2 JAN 2023,5:15 PM
2,NaN,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Wankhede Stadium,",3 JAN 2023,7:00 PM
3,NaN,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,"Steyn City School Ground,",4 JAN 2023,1:30 PM
4,NaN,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Maharashtra Cricket Association Stadium,",5 JAN 2023,7:00 PM
5,NaN,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Saurashtra Cricket Association Stadium,",7 JAN 2023,7:00 PM
6,NaN,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Barsapara Cricket Stadium,",10 JAN 2023,1:30 PM
7,NaN,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Eden Gardens,",12 JAN 2023,1:30 PM

Q3. Scrape the details of selenium exception from guru99.com.\
Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [11]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="b7b1c748aa671c25fb53eb4ccc290a6a")>

In [12]:
# Using webdriver we'll now open the selenium exception handling page chrome
driver.get("https://www.guru99.com/")
driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a').click()

driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong').click()
time.sleep(5)


Name=[]
Description=[]

guru99=driver.find_elements(By.XPATH,'//p//strong')
for i in guru99:
    Name.append(i.text)


guru99=driver.find_elements(By.XPATH,'//div[@class="entry-content single-content"]//p')
for i in guru99:
    Description.append(i.text)


Desc=[]
for i in range(2,43):
    Desc.append(Description[i].split(':')[1])


Data={'Name':Name[1:42],'Description':Desc}

df=pd.DataFrame(Data)

df

,Name,Description
0,1. ElementNotVisibleException:,This type of Selenium exception occurs when a...
1,2. ElementNotSelectableException:,This Selenium exception occurs when an elemen...
2,3. NoSuchElementException:,This Exception occurs if an element could not...
3,4. NoSuchFrameException:,This Exception occurs if the frame target to ...
4,5. NoAlertPresentException:,This Exception occurs when you switch to no p...
5,6. NoSuchWindowException:,This Exception occurs if the window target to...
6,7. StaleElementReferenceException:,This Selenium exception occurs happens when t...
7,8. SessionNotFoundException:,The WebDriver is acting after you quit the br...
8,9. TimeoutException:,Thrown when there is not enough time for a co...
9,10. WebDriverException:,This Exception takes place when the WebDriver...
10,11. ConnectionClosedException:,This type of Exception takes place when there...
11,12. ElementClickInterceptedException:,The command may not be completed as the eleme...
12,13. ElementNotInteractableException:,This Selenium exception is thrown when any el...
13,14. ErrorInResponseException:,This happens while interacting with the Firef...
14,15. ErrorHandler.UnknownServerException:,Exception is used as a placeholder in case if...
15,16. ImeActivationFailedException:,This expectation will occur when IME engine a...
16,17. ImeNotAvailableException:,It takes place when IME support is unavailable.
17,18. InsecureCertificateException:,Navigation made the user agent to hit a certi...
18,19. InvalidArgumentException:,It occurs when an argument does not belong to...
19,20. InvalidCookieDomainException:,This happens when you try to add a cookie und...
20,21. InvalidCoordinatesException:,This type of Exception matches an interacting...
21,22. InvalidElementStateException:,It occurs when command can’t be finished when...
22,23. InvalidSessionIdException:,This Exception took place when the given sess...
23,24. InvalidSwitchToTargetException:,This occurs when the frame or window target t...
24,25. JavascriptException:,This issue occurs while executing JavaScript ...
25,26. JsonException:,It occurs when you afford to get the session ...
26,27. NoSuchAttributeException:,This kind of Exception occurs when the attrib...
27,28. MoveTargetOutOfBoundsException:,It takes place if the target provided to the ...
28,29. NoSuchContextException:,ContextAware does mobile device testing.
29,30. NoSuchCookieException:,This Exception occurs when no cookie matching...
30,31. NotFoundException:,This Exception is a subclass of WebDriverExce...
31,32. RemoteDriverServerException:,This Selenium exception is thrown when the se...
32,33. ScreenshotException:,It is not possible to capture a screen.
33,34. SessionNotCreatedException:,It happens when a new session could not be su...
34,35. UnableToSetCookieException:,This occurs if a driver is unable to set a co...
35,36. UnexpectedTagNameException:,Happens if a support class did not get a web ...
36,37. UnhandledAlertException:,This expectation occurs when there is an aler...
37,38. UnexpectedAlertPresentException:,It occurs when there is the appearance of an ...
38,39. UnknownMethodException:,This Exception happens when the requested com...
39,40. UnreachableBrowserException:,This Exception occurs only when the browser i...
40,41. UnsupportedCommandException:,This occurs when remote WebDriver doesn’t sen...

In [13]:
driver.close

Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP(18-19)- at current prices

D) GSDP(19-20)- at current prices

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [14]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="21d31b9d76ebc36c67035de6cdec90ee")>

In [15]:
# Getting the webpage of mentioned url 
url = "http://statisticstimes.com/"
driver.get(url)

In [16]:
#Clicking on economy section
economy = driver.find_element(By.XPATH,'//div[@class="navbar"]//div[2]//button').click()

urls = driver.find_element(By.XPATH,'//div[@class="dropdown-content"]//a[3]')
ineco_page = urls.get_attribute("href")
#Going to indian economy page
driver.get(ineco_page)  
time.sleep(5)

In [17]:
#Creating empty list
Rank = []
State = []
GSDP_1 = []
GSDP_2 = []
Share = []
GDP = []

In [18]:
#get the url of page containing GDP of indian states
sta_GDP = driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li/a')
GDP_url = sta_GDP.get_attribute("href")

driver.get(GDP_url)
time.sleep(6)


#Scraping data of rank
for i in driver.find_elements(By.XPATH,'//div[@id="table_id_wrapper"]//tbody//tr//td[1]'):
    Rank.append(i.text)

    
#Scraping data of state name
for i in driver.find_elements(By.XPATH,'//div[@id="table_id_wrapper"]//tbody//tr//td[2]'):
    State.append(i.text)

    
# Scraping data of GSDP at current price (18-19)
for i in driver.find_elements(By.XPATH,'//div[@id="table_id_wrapper"]//tbody//tr//td[3]'):
    GSDP_1.append(i.text)

    
#Scraping data of GSDP at current price (19-20)
for i in driver.find_elements(By.XPATH,'//div[@id="table_id_wrapper"]//tbody//tr//td[4]'):
    GSDP_2.append(i.text)

    
#Scraping data of Share(18-19)
for i in driver.find_elements(By.XPATH,'//div[@id="table_id_wrapper"]//tbody//tr//td[5]'):
    Share.append(i.text)

    
#Scraping data of GDP($ billion)
for i in driver.find_elements(By.XPATH,'//div[@id="table_id_wrapper"]//tbody//tr//td[6]'):
    GDP.append(i.text)

In [19]:
#DataFraming
data=list(zip(Rank,State,GSDP_1,GSDP_2,Share,GDP))

In [21]:
df=pd.DataFrame(data,columns=['Rank','Indian_State','GSDP(18-19)','GSDP(19-20)','Share','GDP'])

In [23]:
df

   Rank               Indian_State GSDP(18-19) GSDP(19-20)   Share      GDP
0     1                Maharashtra           -   2,632,792  13.94%  399.921
1     2                 Tamil Nadu   1,845,853   1,630,208   8.63%  247.629
2     3              Uttar Pradesh   1,687,818   1,584,764   8.39%  240.726
3     4                    Gujarat           -   1,502,899   7.96%  228.290
4     5                  Karnataka   1,631,977   1,493,127   7.91%  226.806
5     6                West Bengal   1,253,832   1,089,898   5.77%  165.556
6     7                  Rajasthan   1,020,989     942,586   4.99%  143.179
7     8             Andhra Pradesh     972,782     862,957   4.57%  131.083
8     9                  Telangana     969,604     861,031   4.56%  130.791
9    10             Madhya Pradesh     906,672     809,592   4.29%  122.977
10   11                     Kerala           -     781,653   4.14%  118.733
11   12                      Delhi     856,112     774,870   4.10%  117.703
12   13                    Haryana     831,610     734,163   3.89%  111.519
13   14                      Bihar     611,804     530,363   2.81%   80.562
14   15                     Punjab     574,760     526,376   2.79%   79.957
15   16                     Odisha     521,275     487,805   2.58%   74.098
16   17                      Assam           -     315,881   1.67%   47.982
17   18               Chhattisgarh     329,180     304,063   1.61%   46.187
18   19                  Jharkhand     328,598     297,204   1.57%   45.145
19   20                Uttarakhand           -     245,895   1.30%   37.351
20   21            Jammu & Kashmir           -     155,956   0.83%   23.690
21   22           Himachal Pradesh     165,472     153,845   0.81%   23.369
22   23                        Goa      80,449      73,170   0.39%   11.115
23   24                    Tripura      55,984      49,845   0.26%    7.571
24   25                 Chandigarh           -      42,114   0.22%    6.397
25   26                 Puducherry      38,253      34,433   0.18%    5.230
26   27                  Meghalaya      36,572      33,481   0.18%    5.086
27   28                     Sikkim      32,496      28,723   0.15%    4.363
28   29                    Manipur      31,790      27,870   0.15%    4.233
29   30                   Nagaland           -      27,283   0.14%    4.144
30   31          Arunachal Pradesh           -      24,603   0.13%    3.737
31   32                    Mizoram      26,503      22,287   0.12%    3.385
32   33  Andaman & Nicobar Islands           -           -       -        -

Q5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language use

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [61]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="18c00504773c770ddb0458022d3e1a1c")>

In [62]:
#getting the desired webpage.
url='https://github.com/'
driver.get(url)
time.sleep(2)

In [63]:
#Getting explore button and clicking on it
explore = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details")

#Selecting trending option
trend_url = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2)    
    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    
    
for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
     #scraping repositories discription
    try:          
        repo_desc.append(driver.find_element(By.XPATH,"/html/body/div[4]/div/main/turbo-frame/div/div/div/div[3]/div[2]/div/div[1]/div/p").text)
    except:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element(By.XPATH,"//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements(By.XPATH,"//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details"}
  (Session info: chrome=108.0.5359.125)
Stacktrace:
Backtrace:
	(No symbol) [0x00D8F243]
	(No symbol) [0x00D17FD1]
	(No symbol) [0x00C0D04D]
	(No symbol) [0x00C3C0B0]
	(No symbol) [0x00C3C22B]
	(No symbol) [0x00C6E612]
	(No symbol) [0x00C585D4]
	(No symbol) [0x00C6C9EB]
	(No symbol) [0x00C58386]
	(No symbol) [0x00C3163C]
	(No symbol) [0x00C3269D]
	GetHandleVerifier [0x01029A22+2655074]
	GetHandleVerifier [0x0101CA24+2601828]
	GetHandleVerifier [0x00E38C0A+619850]
	GetHandleVerifier [0x00E37830+614768]
	(No symbol) [0x00D205FC]
	(No symbol) [0x00D25968]
	(No symbol) [0x00D25A55]
	(No symbol) [0x00D3051B]
	BaseThreadInitThunk [0x74A9FE09+25]
	RtlGetAppContainerNamedObjectPath [0x771C607D+237]
	RtlGetAppContainerNamedObjectPath [0x771C604D+189]

Q6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [47]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="55a385a20b0fffc8fcbcc11265b9e13d")>

In [48]:
# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)

In [51]:
#Clicking on charts
driver.find_element(By.XPATH,"/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]").click()

In [53]:
# clicking view chart
driver.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[2]/div/div[2]/div[3]/a").click()

In [54]:
#Creating empty list
Name = []
Artist = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [55]:
#scraping song names
try:
    names=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//h3')
    for i in names:
        Name.append(i.text)
except NoSuchElementException:       
    Name.append('No details available')
time.sleep(2)    
Name[::4][:100]

[]

In [56]:
#scraping artist names
try:
    artist=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//span')
    for i in artist:
        Artist.append(i.text)
except NoSuchElementException:     
    Artist.append('-')
time.sleep(2)    
Artist[::7][:100]

[]

In [57]:
#scraping last week rank of the song
try:
    last_rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
    for i in last_rank:
        Last_week_rank.append(i.text)
except NoSuchElementException:      
    Last_week_rank.append('-')
    time.sleep(2)    
Last_week_rank[::2][:100]

[]

In [58]:
#scraping song's peak rank
try:
    peak=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"]')
    for i in peak:
        Peak_rank.append(i.text)
except NoSuchElementException:       
    Peak_rank.append('-')
time.sleep(2)    
Peak_rank[1::2][:100]

[]

In [59]:
#scraping number of weeks on board
try:
    weeks=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
    for i in weeks:
        Weeks_on_board.append(i.text)
except NoSuchElementException:       #handling no such element exception
    Weeks_on_board.append('-')
time.sleep(2)    
Weeks_on_board[1::2][:100]

[]

In [60]:
df=pd.DataFrame({'Song_Name':Name[::4][:100],
                'Artist_Name':Artist[::7][:100],
                'Last_week_rank':Last_week_rank[::2][:100],
                'Peak':Peak_rank[1::2][:100],
                'Weeks_on_chart':Weeks_on_board[1::2][:100]})
df

Empty DataFrame
Columns: [Song_Name, Artist_Name, Last_week_rank, Peak, Weeks_on_chart]
Index: []

Q7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [29]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="552a43cc23480cd819ba722d49a1c3f2")>

In [30]:
# Connecting the website
url = " https://www.naukri.com/hr-recruiters-consultants"
driver.get(url)
time.sleep(2)

In [31]:
#clicking on recruiters link
recruiters=driver.find_element(By.XPATH,"//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

In [32]:
#accesing search bar
search=driver.find_element(By.XPATH,"//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

In [33]:
#clicking on search button
button=driver.find_element(By.XPATH,"//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

In [34]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [35]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)


#Scraping data of Designation

for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(i.text)
    

#Scraping data of company name

for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

    
#Scraping data of locations

for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

In [36]:
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 148

In [37]:
# Creating dataframe 
Naukri=pd.DataFrame({})

Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Anik Agrawal
10,Kalpana Dumpala,Executive Hiring,Innominds Software,Company Recruiter
11,Mubarak,Company HR,MoneyTap,Ahmedabad
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,subhas patel
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Founder CEO
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,UK - (london)
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,Recruitment Lead Consultant
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Vadodara / Baroda
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,Trivandrum
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Asif Lucknowi
25,Shaun Rao,Manager Human Resources,Exela Technologies,Director
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,Indore
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,InstaFinancials
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Human Resource
29,kumar,Proprietor,trainin,Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,Kalpana Dumpala
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Executive Hiring
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Hyderabad / Secunderabad
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mubarak
34,Avodha,Business Development Associate,Nikitha Palaparthi,Company HR
35,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore
36,Amit Sharma,Consultant,ASCO consulting,Kushal Rastogi
37,Kanan,senior technology instructor,NY INST,Company HR
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Mumbai
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,Mahesh Babu Channa
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,HR Team Lead
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Hyderabad / Secunderabad
42,Ankit Sinha,Head Analytics,Suntech Global,Vaishnavi Kudalkar
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,HR Executive
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Mumbai
45,Ashwini,Director Global Delivery,MRP Advisers,Priyanka Akiri
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,HR Manager
47,Rajani Nagaraj,HR Manager,WildJasmine,Hyderabad
48,ROHIT Kumar,Architect,LNT Private Limited,Kapil Devang
49,Amir Chowdhury,Managing Partner,Granular.ai,HR Manager

Q8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [38]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="80cf60d05ecc5a8df522f162f79117e2")>

In [39]:
# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

In [40]:
#Creating empty list
Book_name = []
Author = []
Volumes_sold = []
Publisher = []
Genre = []

In [41]:
#scraping data of book names
for i in driver.find_elements(By.XPATH,"//tbody//tr/td[2]"):
    Book_name.append(i.text)

    
#Scraping data of author names
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author.append(i.text)
    except NoSuchElementException:
        Author.append('-')
time.sleep(1)


#Scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[4]"):
    Volumes_sold.append(i.text)

    
#Scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[5]"):
    Publisher.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[6]"):
    Genre.append(i.text)

In [42]:
#DATA FRAMEING
Novel=pd.DataFrame({})
Novel['Book Name'] = Book_name
Novel['Author'] = Author
Novel['Volume sold'] = Volumes_sold
Novel['Publisher'] = Publisher
Novel['Genre'] = Genre
Novel

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [27]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="240baf6ceceb4e98c7d26fe179d79d14")>

In [28]:
# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

In [29]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [30]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

    
#Scraping data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)

    
#Scraping data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
#Scraping data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)

    
#Scraping data of votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [31]:
#DATA FRAMEING
IMDB=pd.DataFrame({})
IMDB['Name'] = Name
IMDB['Year Span'] = Year_span
IMDB['Genre'] = Genre
IMDB['Run Time'] = Run_time
IMDB['Ratings'] = Ratings
IMDB['Votes'] = Votes
IMDB

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,099,515"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,189,757"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"993,882"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"294,127"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"253,250"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,362"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,951"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"199,847"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,701"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"246,863"

Q10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code

In [32]:
# Importing necessary Libraries
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

s=Service("C:/Users/Downloads/chromedriver.exe")
driver=webdriver.Chrome(service=s)
print(driver)
import pandas as pd
from selenium.webdriver.common.by import By 
import time
from selenium.common.exceptions import NoSuchElementException

<selenium.webdriver.chrome.webdriver.WebDriver (session="f75d46cbd87ed45c29577c8c9ff754c5")>

In [33]:
# Opening the uci.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

In [34]:
#Finding view all dataset button
view_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")    
page_url = view_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(5)

#Getting page urls containing list of all datasets
all_lst = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
lst_url = all_lst.get_attribute("href")           
driver.get(lst_url)
time.sleep(5)

#fetching url for each dataset
data_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")    

urls = []     
for i in data_url:
    urls.append(i.get_attribute("href"))

In [35]:
#table view
table = driver.find_element(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a')
table.click()

In [36]:
#Creating empty list
Data_name = []
Data_type = []
Task = []
Attr_type = []
Instances = []
n_attributes = []
Year = []

In [38]:
#Scraping requiredinfo from urls
for i in urls:
    driver.get(i)
    time.sleep(3)
    
    
    #Scraping Dataset name
    try: 
        ds_name = driver.find_element(By.XPATH,"//span[@class='heading']")
        Data_name.append(ds_name.text)
    except NoSuchElementException:
        Data_name.append('-')
    time.sleep(1)
    
    
    #Scraping data type
    try:
         dtype = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if dtype.text == "N/A": raise NoSuchElementException
        Data_type.append(dtype.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(1)
    
    
    #Scraping Attribute type
    try:
        atype = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if atype.text == "N/A": raise NoSuchElementException
        Attr_type.append(atype.text)
    except NoSuchElementException:
        Attr_type.append('-')
    time.sleep(1)
      #scraping Task
    try:
        task = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(1)
    
    
    #Scraping No of instances
    try:
        inst = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if inst.text == "N/A": raise NoSuchElementException
        Instances.append(inst.text)
    except NoSuchElementException:
        Instances.append('-')
    time.sleep(1)
    
    
    #Scraping  No of attribute
    try:
        attr = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attr.text == "N/A": raise NoSuchElementException
        n_attributes.append(attr.text)
    except NoSuchElementException:
        n_attributes.append('-')
    time.sleep(1)
    
    
    #scraping year
    try:
        year = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(1)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 19)

In [39]:
#DATA FRAMING
UCI=pd.DataFrame({})
UCI['Data Name'] = Data_name
UCI['Data Type'] = Data_type
UCI['Task'] = Task
UCI['Attribute type'] = Attr_type
UCI['No of instance'] = Instances
UCI['No of attributes'] = n_attributes
UCI['Year'] = Year
UCI

Empty DataFrame
Columns: [Data Name, Data Type, Task, Attribute type, No of instance, No of attributes, Year]
Index: []